dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - ffmpeg -hwaccels
install:
  - pip install -r requirements.txt

script: pytest